### ISSUE TITLE
Monte carlo dropout may be misleading

### ISSUE THREAD

**Issue by pritesh-mehta** [fepegar/unet#27]
https://github.com/fepegar/unet/blob/9f64483d351b4f7d95c0d871aa7aa587b8fdb21b/unet/unet.py#L32

Monte carlo dropout refers more generally to dropout used during test time, in addition to train time, in order to produce a distribution of outputs whose uncertainty can be measured. The monte carlo dropout argument implemented here is a specific implementation from the paper "On the Compactness, Efficiency, and Representation of 3D Convolutional Networks: Brain Parcellation as a Pretext Task". It may be better to rename as "monte carlo dropout layer" to reflect its use.

**Comment by fepegar** [comment]
Hi, @pritesh-mehta. Ideally, I would write docs for this repo. I'd rather leave this as is now, so the API is not broken. Thanks for the suggestion, though!
