### ISSUE TITLE
3D Unet size mismatch

### ISSUE THREAD

**Issue by kissievendor** [fepegar/unet#28]
* unet version: latest version
* Python version: 3.6.9
* Operating System: Linux

### Description

I am using your 3D unet to train on images of size (256, 256, 256)

### What I Did
I am using MONAI and pytorch for this. Since MONAI's UNet is not completely correct, I've decided to test yours. 
However, I am getting the error.
Sizes of tensor must match except in dimension 2. Got 48 and 49 (The offending index is 0). 

I am assuming the input as batch size and then channels, so (1, 1, 256, 256, 256). 

But what is going wrong here?

Thank you.

**Comment by fepegar** [comment]
Hi, @kissievendor. I'm a bit late, sorry. I just noticed today that I wasn't watching this repo for some reason.

The size of your input should be a multiple of `2 ** n`, where `n` is the number of levels in your U-Net. You can use TorchIO's [`EnsureShapeMultiple`](https://torchio.readthedocs.io/transforms/preprocessing.html#ensureshapemultiple) for that.

Please let me know if you need any more info.
