### ISSUE TITLE
How to cite

### ISSUE THREAD

**Issue by pritesh-mehta** [fepegar/unet#30]
Hi,

Could you explain how to cite if I have used this code. I am unsure how to use the information available in the Zenodo entry as suggested by the readme. 

Thanks,
Pritesh

**Comment by fepegar** [comment]
Hi, @pritesh-mehta. If you go to the Zenodo entry, you'll see the following:

> **Cite as**
> Pérez-García, Fernando. (2020). fepegar/unet: PyTorch implementation of 2D and 3D U-Net (v0.7.5). Zenodo. https://doi.org/10.5281/zenodo.3697931
