### ISSUE TITLE
Is the 1D implementation still available?

### ISSUE THREAD

**Issue by kristiantorres** [fepegar/unet#35]
Is the 1D implementation still available?

Thanks!

**Comment by fepegar** [comment]
Hi, @kristiantorres. Have you tried?

**Comment by kristiantorres** [comment]
Yes, I noticed that the 1D implementation could be missing. For example, when I try
```
from unet import UNet
model = UNet(dimensions=1)
```
I get the following error `UnboundLocalError: local variable 'out_channels_second' referenced before assignment`.

The "About" section says "1D, 2D and 3D", but the README only shows "2D and 3D", so I wondered if you discarded the 1D implementation.

Excellent code and initiative anyways! 

Cheers,

**Comment by fepegar** [comment]
You're right, the code only checks for 2 or 3 dimensions to set some parameters. But it would be very easy to extend the checks for 1D as well. You'd need to add the condition in places like

https://github.com/fepegar/unet/blob/6d3f74b49a4c896ed33f9b28e434d192e311fe62/unet/unet.py#L80-L84

and

https://github.com/fepegar/unet/blob/6d3f74b49a4c896ed33f9b28e434d192e311fe62/unet/encoding.py#L111-L114

Would you like to contribute with a PR?

**Comment by fepegar** [comment]
@AndreyPikunov has added support in #38.
