### ISSUE TITLE
python 3.13

### ISSUE THREAD

**Issue by dvolgyes** [fepegar/unet#43]
Hi,

Quick question: is there any reason not to support python 3.13?
I see it twice in the pyproject.toml, once in `requires-python`, 
once in `classifiers`. 
Correct me if I am wrong, but torch should be able to handle the python parts,
so technically you could even support python 3.14alpha versions as long as the 
torch package is properly present.
My proposal is: extend the python range, even if there is no pytorch yet for a given python version:
that's torch's dependency, not your package's.

**Comment by fepegar** [comment]
Fixed in `v0.8.1`.

Thanks, @dvolgyes. Always a pleasure to learn from you.
